### ISSUE TITLE
Build time styles / FastBoot compatibility

### ISSUE THREAD

**Issue by vlascik** [rajasegar/ember-csz#2]
So, I'm using utility class CSS frameworks like Tailwind and BS4 utilities, which works mostly fine, but the approach has its limits. I'm looking for a better replacement for the occasional need for inline styles, e.g. `<div style="height: 53px; width: "74px;">`. 

This addon has a pretty good syntax, `{{csz}}` helper could be exactly what's needed. But, manipulating styles at runtime via JS can be problematic, especially with FastBoot.

How about if this addon compiled a list of static classes and related styles from templates at build? Every time it would encounter {{csz}} helper in a template, it could extract the styles and put them into a generated "csz-styles.css" file you could import from your app.(s)css. `ember-component-css` does something similar. In addition, it would require some AST manipulation, e.g. with `ember-template-recast`.

That way, `ember-csz` wouldn't need to add styles to `<head>` and wouldn't break in FastBoot thanks to manipulating non-existent `document` object.

**Comment by rajasegar** [comment]
Sounds like a good idea to me, but the goal of csz is to generate class names in run time rather than during compile time. It was mean't to run in the browser on the fly. I am not sure adding Fastboot compatibility will align to those goals. Anyway I am happy to accept any PR for the same. We will discuss once we finalize on the implementation approach.

**Comment by vlascik** [comment]
Yeah, this use case would probably be better served by a separate addon and AST transforms. I'm going to close this issue.
